// 台灣國中英文基礎1200單字匯入腳本

// 確保全局數據已初始化
if (!window.appData) {
    window.appData = {
        vocabulary: []
    };
}

// 確保 vocabulary 是一個陣列
if (!window.appData.vocabulary) {
    window.appData.vocabulary = [];
} else if (!Array.isArray(window.appData.vocabulary)) {
    window.appData.vocabulary = [];
}

// 台灣國中英文基礎1200單字
const basic1200Words = [
    // A
    { word: "a", meaning: "一個", partOfSpeech: "art" },
    { word: "able", meaning: "能夠的", partOfSpeech: "adj" },
    { word: "about", meaning: "關於", partOfSpeech: "prep" },
    { word: "above", meaning: "在...之上", partOfSpeech: "prep" },
    { word: "abroad", meaning: "在國外", partOfSpeech: "adv" },
    { word: "absent", meaning: "缺席的", partOfSpeech: "adj" },
    { word: "accept", meaning: "接受", partOfSpeech: "v" },
    { word: "accident", meaning: "事故", partOfSpeech: "n" },
    { word: "across", meaning: "穿過", partOfSpeech: "prep" },
    { word: "act", meaning: "行動", partOfSpeech: "v" },
    { word: "action", meaning: "行動", partOfSpeech: "n" },
    { word: "active", meaning: "活躍的", partOfSpeech: "adj" },
    { word: "activity", meaning: "活動", partOfSpeech: "n" },
    { word: "actor", meaning: "男演員", partOfSpeech: "n" },
    { word: "actress", meaning: "女演員", partOfSpeech: "n" },
    { word: "add", meaning: "添加", partOfSpeech: "v" },
    { word: "address", meaning: "地址", partOfSpeech: "n" },
    { word: "admire", meaning: "欽佩", partOfSpeech: "v" },
    { word: "adult", meaning: "成年人", partOfSpeech: "n" },
    { word: "advertisement", meaning: "廣告", partOfSpeech: "n" },
    { word: "advice", meaning: "建議", partOfSpeech: "n" },
    { word: "afraid", meaning: "害怕的", partOfSpeech: "adj" },
    { word: "after", meaning: "在...之後", partOfSpeech: "prep" },
    { word: "afternoon", meaning: "下午", partOfSpeech: "n" },
    { word: "again", meaning: "再次", partOfSpeech: "adv" },
    { word: "against", meaning: "反對", partOfSpeech: "prep" },
    { word: "age", meaning: "年齡", partOfSpeech: "n" },
    { word: "ago", meaning: "...之前", partOfSpeech: "adv" },
    { word: "agree", meaning: "同意", partOfSpeech: "v" },
    { word: "ahead", meaning: "在前面", partOfSpeech: "adv" },
    { word: "air", meaning: "空氣", partOfSpeech: "n" },
    { word: "airplane", meaning: "飛機", partOfSpeech: "n" },
    { word: "airport", meaning: "機場", partOfSpeech: "n" },
    { word: "all", meaning: "全部", partOfSpeech: "adj" },
    { word: "allow", meaning: "允許", partOfSpeech: "v" },
    { word: "almost", meaning: "幾乎", partOfSpeech: "adv" },
    { word: "alone", meaning: "單獨的", partOfSpeech: "adj" },
    { word: "along", meaning: "沿著", partOfSpeech: "prep" },
    { word: "already", meaning: "已經", partOfSpeech: "adv" },
    { word: "also", meaning: "也", partOfSpeech: "adv" },
    { word: "although", meaning: "雖然", partOfSpeech: "conj" },
    { word: "always", meaning: "總是", partOfSpeech: "adv" },
    { word: "am", meaning: "是", partOfSpeech: "v" },
    { word: "among", meaning: "在...之中", partOfSpeech: "prep" },
    { word: "amount", meaning: "數量", partOfSpeech: "n" },
    { word: "and", meaning: "和", partOfSpeech: "conj" },
    { word: "angry", meaning: "生氣的", partOfSpeech: "adj" },
    { word: "animal", meaning: "動物", partOfSpeech: "n" },
    { word: "another", meaning: "另一個", partOfSpeech: "adj" },
    { word: "answer", meaning: "回答", partOfSpeech: "n" },
    
    // B
    { word: "baby", meaning: "嬰兒", partOfSpeech: "n" },
    { word: "back", meaning: "背部", partOfSpeech: "n" },
    { word: "bad", meaning: "壞的", partOfSpeech: "adj" },
    { word: "bag", meaning: "包", partOfSpeech: "n" },
    { word: "ball", meaning: "球", partOfSpeech: "n" },
    { word: "balloon", meaning: "氣球", partOfSpeech: "n" },
    { word: "banana", meaning: "香蕉", partOfSpeech: "n" },
    { word: "band", meaning: "樂隊", partOfSpeech: "n" },
    { word: "bank", meaning: "銀行", partOfSpeech: "n" },
    { word: "baseball", meaning: "棒球", partOfSpeech: "n" },
    { word: "basketball", meaning: "籃球", partOfSpeech: "n" },
    { word: "bath", meaning: "洗澡", partOfSpeech: "n" },
    { word: "bathroom", meaning: "浴室", partOfSpeech: "n" },
    { word: "be", meaning: "是", partOfSpeech: "v" },
    { word: "beach", meaning: "海灘", partOfSpeech: "n" },
    { word: "bear", meaning: "熊", partOfSpeech: "n" },
    { word: "beautiful", meaning: "美麗的", partOfSpeech: "adj" },
    { word: "because", meaning: "因為", partOfSpeech: "conj" },
    { word: "become", meaning: "變成", partOfSpeech: "v" },
    { word: "bed", meaning: "床", partOfSpeech: "n" },
    { word: "bedroom", meaning: "臥室", partOfSpeech: "n" },
    { word: "bee", meaning: "蜜蜂", partOfSpeech: "n" },
    { word: "beef", meaning: "牛肉", partOfSpeech: "n" },
    { word: "before", meaning: "在...之前", partOfSpeech: "prep" },
    { word: "begin", meaning: "開始", partOfSpeech: "v" },
    { word: "behind", meaning: "在...後面", partOfSpeech: "prep" },
    { word: "believe", meaning: "相信", partOfSpeech: "v" },
    { word: "bell", meaning: "鈴", partOfSpeech: "n" },
    { word: "belong", meaning: "屬於", partOfSpeech: "v" },
    { word: "below", meaning: "在...下面", partOfSpeech: "prep" },
    { word: "belt", meaning: "腰帶", partOfSpeech: "n" },
    { word: "beside", meaning: "在...旁邊", partOfSpeech: "prep" },
    { word: "between", meaning: "在...之間", partOfSpeech: "prep" },
    { word: "bicycle", meaning: "自行車", partOfSpeech: "n" },
    { word: "big", meaning: "大的", partOfSpeech: "adj" },
    { word: "bike", meaning: "自行車", partOfSpeech: "n" },
    { word: "bird", meaning: "鳥", partOfSpeech: "n" },
    { word: "birthday", meaning: "生日", partOfSpeech: "n" },
    { word: "black", meaning: "黑色的", partOfSpeech: "adj" },
    { word: "blackboard", meaning: "黑板", partOfSpeech: "n" },
    { word: "blanket", meaning: "毯子", partOfSpeech: "n" },
    { word: "blind", meaning: "盲的", partOfSpeech: "adj" },
    { word: "block", meaning: "街區", partOfSpeech: "n" },
    { word: "blood", meaning: "血液", partOfSpeech: "n" },
    { word: "blouse", meaning: "女式襯衫", partOfSpeech: "n" },
    { word: "blow", meaning: "吹", partOfSpeech: "v" },
    { word: "blue", meaning: "藍色的", partOfSpeech: "adj" },
    { word: "boat", meaning: "船", partOfSpeech: "n" },
    { word: "body", meaning: "身體", partOfSpeech: "n" },
    { word: "book", meaning: "書", partOfSpeech: "n" },
    { word: "bookstore", meaning: "書店", partOfSpeech: "n" },
    
    // C
    { word: "cake", meaning: "蛋糕", partOfSpeech: "n" },
    { word: "call", meaning: "打電話", partOfSpeech: "v" },
    { word: "camera", meaning: "相機", partOfSpeech: "n" },
    { word: "camp", meaning: "露營", partOfSpeech: "n" },
    { word: "can", meaning: "能夠", partOfSpeech: "v" },
    { word: "candy", meaning: "糖果", partOfSpeech: "n" },
    { word: "cap", meaning: "帽子", partOfSpeech: "n" },
    { word: "car", meaning: "汽車", partOfSpeech: "n" },
    { word: "card", meaning: "卡片", partOfSpeech: "n" },
    { word: "care", meaning: "關心", partOfSpeech: "v" },
    { word: "careful", meaning: "小心的", partOfSpeech: "adj" },
    { word: "carry", meaning: "攜帶", partOfSpeech: "v" },
    { word: "case", meaning: "情況", partOfSpeech: "n" },
    { word: "cat", meaning: "貓", partOfSpeech: "n" },
    { word: "catch", meaning: "抓住", partOfSpeech: "v" },
    { word: "celebrate", meaning: "慶祝", partOfSpeech: "v" },
    { word: "cell", meaning: "細胞", partOfSpeech: "n" },
    { word: "cent", meaning: "分(錢)", partOfSpeech: "n" },
    { word: "center", meaning: "中心", partOfSpeech: "n" },
    { word: "chair", meaning: "椅子", partOfSpeech: "n" },
    { word: "chance", meaning: "機會", partOfSpeech: "n" },
    { word: "change", meaning: "改變", partOfSpeech: "v" },
    { word: "cheap", meaning: "便宜的", partOfSpeech: "adj" },
    { word: "check", meaning: "檢查", partOfSpeech: "v" },
    { word: "cheer", meaning: "歡呼", partOfSpeech: "v" },
    { word: "cheese", meaning: "起司", partOfSpeech: "n" },
    { word: "chicken", meaning: "雞肉", partOfSpeech: "n" },
    { word: "child", meaning: "孩子", partOfSpeech: "n" },
    { word: "chocolate", meaning: "巧克力", partOfSpeech: "n" },
    { word: "choose", meaning: "選擇", partOfSpeech: "v" },
    { word: "Christmas", meaning: "聖誕節", partOfSpeech: "n" },
    { word: "church", meaning: "教堂", partOfSpeech: "n" },
    { word: "circle", meaning: "圓圈", partOfSpeech: "n" },
    { word: "city", meaning: "城市", partOfSpeech: "n" },
    { word: "class", meaning: "班級", partOfSpeech: "n" },
    { word: "classmate", meaning: "同學", partOfSpeech: "n" },
    { word: "classroom", meaning: "教室", partOfSpeech: "n" },
    { word: "clean", meaning: "乾淨的", partOfSpeech: "adj" },
    { word: "clear", meaning: "清楚的", partOfSpeech: "adj" },
    { word: "climb", meaning: "爬", partOfSpeech: "v" },
    { word: "clock", meaning: "時鐘", partOfSpeech: "n" },
    { word: "close", meaning: "關閉", partOfSpeech: "v" },
    { word: "clothes", meaning: "衣服", partOfSpeech: "n" },
    { word: "cloud", meaning: "雲", partOfSpeech: "n" },
    { word: "cloudy", meaning: "多雲的", partOfSpeech: "adj" },
    { word: "club", meaning: "俱樂部", partOfSpeech: "n" },
    { word: "coat", meaning: "外套", partOfSpeech: "n" },
    { word: "coffee", meaning: "咖啡", partOfSpeech: "n" },
    { word: "cold", meaning: "冷的", partOfSpeech: "adj" },
    { word: "collect", meaning: "收集", partOfSpeech: "v" },
    
    // D
    { word: "dance", meaning: "跳舞", partOfSpeech: "v" },
    { word: "dangerous", meaning: "危險的", partOfSpeech: "adj" },
    { word: "dark", meaning: "黑暗的", partOfSpeech: "adj" },
    { word: "date", meaning: "日期", partOfSpeech: "n" },
    { word: "daughter", meaning: "女兒", partOfSpeech: "n" },
    { word: "day", meaning: "日", partOfSpeech: "n" },
    { word: "dead", meaning: "死的", partOfSpeech: "adj" },
    { word: "dear", meaning: "親愛的", partOfSpeech: "adj" },
    { word: "December", meaning: "十二月", partOfSpeech: "n" },
    { word: "decide", meaning: "決定", partOfSpeech: "v" },
    { word: "delicious", meaning: "美味的", partOfSpeech: "adj" },
    { word: "department", meaning: "部門", partOfSpeech: "n" },
    { word: "desk", meaning: "書桌", partOfSpeech: "n" },
    { word: "dictionary", meaning: "字典", partOfSpeech: "n" },
    { word: "die", meaning: "死亡", partOfSpeech: "v" },
    { word: "different", meaning: "不同的", partOfSpeech: "adj" },
    { word: "difficult", meaning: "困難的", partOfSpeech: "adj" },
    { word: "dinner", meaning: "晚餐", partOfSpeech: "n" },
    { word: "dirty", meaning: "髒的", partOfSpeech: "adj" },
    { word: "dish", meaning: "盤子", partOfSpeech: "n" },
    { word: "do", meaning: "做", partOfSpeech: "v" },
    { word: "doctor", meaning: "醫生", partOfSpeech: "n" },
    { word: "dog", meaning: "狗", partOfSpeech: "n" },
    { word: "doll", meaning: "洋娃娃", partOfSpeech: "n" },
    { word: "dollar", meaning: "美元", partOfSpeech: "n" },
    { word: "door", meaning: "門", partOfSpeech: "n" },
    { word: "down", meaning: "向下", partOfSpeech: "adv" },
    { word: "draw", meaning: "畫", partOfSpeech: "v" },
    { word: "dream", meaning: "夢", partOfSpeech: "n" },
    { word: "dress", meaning: "洋裝", partOfSpeech: "n" },
    { word: "drink", meaning: "喝", partOfSpeech: "v" },
    { word: "drive", meaning: "開車", partOfSpeech: "v" },
    { word: "drop", meaning: "滴落", partOfSpeech: "v" },
    { word: "dry", meaning: "乾的", partOfSpeech: "adj" },
    { word: "during", meaning: "在...期間", partOfSpeech: "prep" },
    
    // E
    { word: "each", meaning: "每個", partOfSpeech: "adj" },
    { word: "ear", meaning: "耳朵", partOfSpeech: "n" },
    { word: "early", meaning: "早的", partOfSpeech: "adj" },
    { word: "earth", meaning: "地球", partOfSpeech: "n" },
    { word: "east", meaning: "東方", partOfSpeech: "n" },
    { word: "easy", meaning: "容易的", partOfSpeech: "adj" },
    { word: "eat", meaning: "吃", partOfSpeech: "v" },
    { word: "egg", meaning: "蛋", partOfSpeech: "n" },
    { word: "eight", meaning: "八", partOfSpeech: "num" },
    { word: "eighteen", meaning: "十八", partOfSpeech: "num" },
    { word: "eighty", meaning: "八十", partOfSpeech: "num" },
    { word: "either", meaning: "兩者之一", partOfSpeech: "conj" },
    { word: "elephant", meaning: "大象", partOfSpeech: "n" },
    { word: "eleven", meaning: "十一", partOfSpeech: "num" },
    { word: "else", meaning: "其他", partOfSpeech: "adv" },
    { word: "email", meaning: "電子郵件", partOfSpeech: "n" },
    { word: "end", meaning: "結束", partOfSpeech: "n" },
    { word: "English", meaning: "英語", partOfSpeech: "n" },
    { word: "enjoy", meaning: "享受", partOfSpeech: "v" },
    { word: "enough", meaning: "足夠的", partOfSpeech: "adj" },
    { word: "enter", meaning: "進入", partOfSpeech: "v" },
    { word: "eraser", meaning: "橡皮擦", partOfSpeech: "n" },
    { word: "even", meaning: "甚至", partOfSpeech: "adv" },
    { word: "evening", meaning: "傍晚", partOfSpeech: "n" },
    { word: "ever", meaning: "曾經", partOfSpeech: "adv" },
    { word: "every", meaning: "每一個", partOfSpeech: "adj" },
    { word: "everyone", meaning: "每個人", partOfSpeech: "pron" },
    { word: "everything", meaning: "每件事", partOfSpeech: "pron" },
    { word: "example", meaning: "例子", partOfSpeech: "n" },
    { word: "excellent", meaning: "優秀的", partOfSpeech: "adj" },
    { word: "except", meaning: "除了", partOfSpeech: "prep" },
    { word: "excited", meaning: "興奮的", partOfSpeech: "adj" },
    { word: "excuse", meaning: "原諒", partOfSpeech: "v" },
    { word: "exercise", meaning: "運動", partOfSpeech: "n" },
    { word: "expensive", meaning: "昂貴的", partOfSpeech: "adj" },
    { word: "experience", meaning: "經驗", partOfSpeech: "n" },
    { word: "explain", meaning: "解釋", partOfSpeech: "v" },
    { word: "eye", meaning: "眼睛", partOfSpeech: "n" },
    
    // F
    { word: "face", meaning: "臉", partOfSpeech: "n" },
    { word: "fact", meaning: "事實", partOfSpeech: "n" },
    { word: "factory", meaning: "工廠", partOfSpeech: "n" },
    { word: "fall", meaning: "落下", partOfSpeech: "v" },
    { word: "family", meaning: "家庭", partOfSpeech: "n" },
    { word: "famous", meaning: "有名的", partOfSpeech: "adj" },
    { word: "fan", meaning: "風扇", partOfSpeech: "n" },
    { word: "far", meaning: "遠的", partOfSpeech: "adj" },
    { word: "farm", meaning: "農場", partOfSpeech: "n" },
    { word: "farmer", meaning: "農夫", partOfSpeech: "n" },
    { word: "fast", meaning: "快的", partOfSpeech: "adj" },
    { word: "fat", meaning: "胖的", partOfSpeech: "adj" },
    { word: "father", meaning: "父親", partOfSpeech: "n" },
    { word: "favorite", meaning: "最喜歡的", partOfSpeech: "adj" },
    { word: "February", meaning: "二月", partOfSpeech: "n" },
    { word: "feed", meaning: "餵食", partOfSpeech: "v" },
    { word: "feel", meaning: "感覺", partOfSpeech: "v" },
    { word: "festival", meaning: "節日", partOfSpeech: "n" },
    { word: "few", meaning: "很少的", partOfSpeech: "adj" },
    { word: "fifteen", meaning: "十五", partOfSpeech: "num" },
    { word: "fifty", meaning: "五十", partOfSpeech: "num" },
    { word: "fill", meaning: "填滿", partOfSpeech: "v" },
    { word: "final", meaning: "最後的", partOfSpeech: "adj" },
    { word: "find", meaning: "找到", partOfSpeech: "v" },
    { word: "fine", meaning: "好的", partOfSpeech: "adj" },
    { word: "finger", meaning: "手指", partOfSpeech: "n" },
    { word: "finish", meaning: "完成", partOfSpeech: "v" },
    { word: "fire", meaning: "火", partOfSpeech: "n" },
    { word: "first", meaning: "第一", partOfSpeech: "num" },
    { word: "fish", meaning: "魚", partOfSpeech: "n" },
    { word: "five", meaning: "五", partOfSpeech: "num" },
    { word: "fix", meaning: "修理", partOfSpeech: "v" },
    { word: "floor", meaning: "地板", partOfSpeech: "n" },
    { word: "flower", meaning: "花", partOfSpeech: "n" },
    { word: "fly", meaning: "飛", partOfSpeech: "v" },
    { word: "follow", meaning: "跟隨", partOfSpeech: "v" },
    { word: "food", meaning: "食物", partOfSpeech: "n" },
    { word: "foot", meaning: "腳", partOfSpeech: "n" },
    { word: "for", meaning: "為了", partOfSpeech: "prep" },
    { word: "foreign", meaning: "外國的", partOfSpeech: "adj" },
    { word: "forget", meaning: "忘記", partOfSpeech: "v" },
    { word: "fork", meaning: "叉子", partOfSpeech: "n" },
    { word: "forty", meaning: "四十", partOfSpeech: "num" },
    { word: "four", meaning: "四", partOfSpeech: "num" },
    { word: "fourteen", meaning: "十四", partOfSpeech: "num" },
    { word: "free", meaning: "免費的", partOfSpeech: "adj" },
    { word: "fresh", meaning: "新鮮的", partOfSpeech: "adj" },
    { word: "Friday", meaning: "星期五", partOfSpeech: "n" },
    { word: "friend", meaning: "朋友", partOfSpeech: "n" },
    { word: "friendly", meaning: "友好的", partOfSpeech: "adj" },
    { word: "from", meaning: "從", partOfSpeech: "prep" },
    { word: "front", meaning: "前面", partOfSpeech: "n" },
    { word: "fruit", meaning: "水果", partOfSpeech: "n" },
    { word: "full", meaning: "滿的", partOfSpeech: "adj" },
    { word: "fun", meaning: "樂趣", partOfSpeech: "n" },
    { word: "funny", meaning: "有趣的", partOfSpeech: "adj" },
    { word: "future", meaning: "未來", partOfSpeech: "n" },
    
    // G
    { word: "game", meaning: "遊戲", partOfSpeech: "n" },
    { word: "garden", meaning: "花園", partOfSpeech: "n" },
    { word: "gas", meaning: "汽油", partOfSpeech: "n" },
    { word: "gate", meaning: "大門", partOfSpeech: "n" },
    { word: "get", meaning: "得到", partOfSpeech: "v" },
    { word: "gift", meaning: "禮物", partOfSpeech: "n" },
    { word: "girl", meaning: "女孩", partOfSpeech: "n" },
    { word: "give", meaning: "給予", partOfSpeech: "v" },
    { word: "glad", meaning: "高興的", partOfSpeech: "adj" },
    { word: "glass", meaning: "玻璃", partOfSpeech: "n" },
    { word: "go", meaning: "去", partOfSpeech: "v" },
    { word: "goat", meaning: "山羊", partOfSpeech: "n" },
    { word: "good", meaning: "好的", partOfSpeech: "adj" },
    { word: "goodbye", meaning: "再見", partOfSpeech: "n" },
    { word: "grade", meaning: "年級", partOfSpeech: "n" },
    { word: "grandfather", meaning: "祖父", partOfSpeech: "n" },
    { word: "grandmother", meaning: "祖母", partOfSpeech: "n" },
    { word: "grass", meaning: "草", partOfSpeech: "n" },
    { word: "gray", meaning: "灰色的", partOfSpeech: "adj" },
    { word: "great", meaning: "偉大的", partOfSpeech: "adj" },
    { word: "green", meaning: "綠色的", partOfSpeech: "adj" },
    { word: "ground", meaning: "地面", partOfSpeech: "n" },
    { word: "group", meaning: "群體", partOfSpeech: "n" },
    { word: "grow", meaning: "成長", partOfSpeech: "v" },
    { word: "guess", meaning: "猜測", partOfSpeech: "v" },
    { word: "guitar", meaning: "吉他", partOfSpeech: "n" },
    
    // H
    { word: "habit", meaning: "習慣", partOfSpeech: "n" },
    { word: "hair", meaning: "頭髮", partOfSpeech: "n" },
    { word: "half", meaning: "一半", partOfSpeech: "n" },
    { word: "hall", meaning: "大廳", partOfSpeech: "n" },
    { word: "hamburger", meaning: "漢堡", partOfSpeech: "n" },
    { word: "hand", meaning: "手", partOfSpeech: "n" },
    { word: "happen", meaning: "發生", partOfSpeech: "v" },
    { word: "happy", meaning: "快樂的", partOfSpeech: "adj" },
    { word: "hard", meaning: "困難的", partOfSpeech: "adj" },
    { word: "hat", meaning: "帽子", partOfSpeech: "n" },
    { word: "hate", meaning: "討厭", partOfSpeech: "v" },
    { word: "have", meaning: "有", partOfSpeech: "v" },
    { word: "he", meaning: "他", partOfSpeech: "pron" },
    { word: "head", meaning: "頭", partOfSpeech: "n" },
    { word: "health", meaning: "健康", partOfSpeech: "n" },
    { word: "healthy", meaning: "健康的", partOfSpeech: "adj" },
    { word: "hear", meaning: "聽見", partOfSpeech: "v" },
    { word: "heart", meaning: "心臟", partOfSpeech: "n" },
    { word: "heavy", meaning: "重的", partOfSpeech: "adj" },
    { word: "hello", meaning: "你好", partOfSpeech: "n" },
    { word: "help", meaning: "幫助", partOfSpeech: "v" },
    { word: "her", meaning: "她的", partOfSpeech: "pron" },
    { word: "here", meaning: "這裡", partOfSpeech: "adv" },
    { word: "hi", meaning: "嗨", partOfSpeech: "int" },
    { word: "hide", meaning: "隱藏", partOfSpeech: "v" },
    { word: "high", meaning: "高的", partOfSpeech: "adj" },
    { word: "hill", meaning: "山丘", partOfSpeech: "n" },
    { word: "him", meaning: "他(受格)", partOfSpeech: "pron" },
    { word: "his", meaning: "他的", partOfSpeech: "pron" },
    { word: "history", meaning: "歷史", partOfSpeech: "n" },
    { word: "hobby", meaning: "嗜好", partOfSpeech: "n" },
    { word: "hold", meaning: "握住", partOfSpeech: "v" },
    { word: "holiday", meaning: "假日", partOfSpeech: "n" },
    { word: "home", meaning: "家", partOfSpeech: "n" },
    { word: "homework", meaning: "家庭作業", partOfSpeech: "n" },
    { word: "hope", meaning: "希望", partOfSpeech: "v" },
    { word: "horse", meaning: "馬", partOfSpeech: "n" },
    { word: "hospital", meaning: "醫院", partOfSpeech: "n" },
    { word: "hot", meaning: "熱的", partOfSpeech: "adj" },
    { word: "hotel", meaning: "飯店", partOfSpeech: "n" },
    { word: "hour", meaning: "小時", partOfSpeech: "n" },
    { word: "house", meaning: "房子", partOfSpeech: "n" },
    { word: "how", meaning: "如何", partOfSpeech: "adv" },
    { word: "hundred", meaning: "百", partOfSpeech: "num" },
    { word: "hungry", meaning: "飢餓的", partOfSpeech: "adj" },
    { word: "hurry", meaning: "匆忙", partOfSpeech: "v" },
    { word: "hurt", meaning: "傷害", partOfSpeech: "v" },
    { word: "husband", meaning: "丈夫", partOfSpeech: "n" },
    
    // I
    { word: "I", meaning: "我", partOfSpeech: "pron" },
    { word: "ice", meaning: "冰", partOfSpeech: "n" },
    { word: "ice cream", meaning: "冰淇淋", partOfSpeech: "n" },
    { word: "idea", meaning: "想法", partOfSpeech: "n" },
    { word: "if", meaning: "如果", partOfSpeech: "conj" },
    { word: "important", meaning: "重要的", partOfSpeech: "adj" },
    { word: "in", meaning: "在...裡", partOfSpeech: "prep" },
    { word: "information", meaning: "資訊", partOfSpeech: "n" },
    { word: "inside", meaning: "裡面", partOfSpeech: "prep" },
    { word: "interest", meaning: "興趣", partOfSpeech: "n" },
    { word: "interesting", meaning: "有趣的", partOfSpeech: "adj" },
    { word: "Internet", meaning: "網際網路", partOfSpeech: "n" },
    { word: "into", meaning: "進入", partOfSpeech: "prep" },
    { word: "invite", meaning: "邀請", partOfSpeech: "v" },
    { word: "island", meaning: "島嶼", partOfSpeech: "n" },
    { word: "it", meaning: "它", partOfSpeech: "pron" },
    { word: "its", meaning: "它的", partOfSpeech: "pron" },
    
    // J
    { word: "jacket", meaning: "夾克", partOfSpeech: "n" },
    { word: "January", meaning: "一月", partOfSpeech: "n" },
    { word: "jeans", meaning: "牛仔褲", partOfSpeech: "n" },
    { word: "job", meaning: "工作", partOfSpeech: "n" },
    { word: "join", meaning: "加入", partOfSpeech: "v" },
    { word: "joke", meaning: "笑話", partOfSpeech: "n" },
    { word: "juice", meaning: "果汁", partOfSpeech: "n" },
    { word: "July", meaning: "七月", partOfSpeech: "n" },
    { word: "jump", meaning: "跳", partOfSpeech: "v" },
    { word: "June", meaning: "六月", partOfSpeech: "n" },
    { word: "just", meaning: "剛剛", partOfSpeech: "adv" },
    
    // K
    { word: "keep", meaning: "保持", partOfSpeech: "v" },
    { word: "key", meaning: "鑰匙", partOfSpeech: "n" },
    { word: "kick", meaning: "踢", partOfSpeech: "v" },
    { word: "kid", meaning: "小孩", partOfSpeech: "n" },
    { word: "kill", meaning: "殺死", partOfSpeech: "v" },
    { word: "kind", meaning: "種類", partOfSpeech: "n" },
    { word: "king", meaning: "國王", partOfSpeech: "n" },
    { word: "kitchen", meaning: "廚房", partOfSpeech: "n" },
    { word: "kite", meaning: "風箏", partOfSpeech: "n" },
    { word: "knee", meaning: "膝蓋", partOfSpeech: "n" },
    { word: "knife", meaning: "刀", partOfSpeech: "n" },
    { word: "know", meaning: "知道", partOfSpeech: "v" },
    { word: "knowledge", meaning: "知識", partOfSpeech: "n" },
    
    // L
    { word: "lake", meaning: "湖", partOfSpeech: "n" },
    { word: "lamp", meaning: "燈", partOfSpeech: "n" },
    { word: "land", meaning: "陸地", partOfSpeech: "n" },
    { word: "language", meaning: "語言", partOfSpeech: "n" },
    { word: "large", meaning: "大的", partOfSpeech: "adj" },
    { word: "last", meaning: "最後的", partOfSpeech: "adj" },
    { word: "late", meaning: "晚的", partOfSpeech: "adj" },
    { word: "later", meaning: "稍後", partOfSpeech: "adv" },
    { word: "laugh", meaning: "笑", partOfSpeech: "v" },
    { word: "lazy", meaning: "懶惰的", partOfSpeech: "adj" },
    { word: "lead", meaning: "領導", partOfSpeech: "v" },
    { word: "learn", meaning: "學習", partOfSpeech: "v" },
    { word: "least", meaning: "最少的", partOfSpeech: "adj" },
    { word: "leave", meaning: "離開", partOfSpeech: "v" },
    { word: "left", meaning: "左邊的", partOfSpeech: "adj" },
    { word: "leg", meaning: "腿", partOfSpeech: "n" },
    { word: "lemon", meaning: "檸檬", partOfSpeech: "n" },
    { word: "lend", meaning: "借出", partOfSpeech: "v" },
    { word: "less", meaning: "較少的", partOfSpeech: "adj" },
    { word: "lesson", meaning: "課", partOfSpeech: "n" },
    { word: "let", meaning: "讓", partOfSpeech: "v" },
    { word: "letter", meaning: "信", partOfSpeech: "n" },
    { word: "library", meaning: "圖書館", partOfSpeech: "n" },
    { word: "lie", meaning: "說謊", partOfSpeech: "v" },
    { word: "life", meaning: "生命", partOfSpeech: "n" },
    { word: "light", meaning: "光", partOfSpeech: "n" },
    { word: "like", meaning: "喜歡", partOfSpeech: "v" },
    { word: "line", meaning: "線", partOfSpeech: "n" },
    { word: "lion", meaning: "獅子", partOfSpeech: "n" },
    { word: "list", meaning: "列表", partOfSpeech: "n" },
    { word: "listen", meaning: "聽", partOfSpeech: "v" },
    { word: "little", meaning: "小的", partOfSpeech: "adj" },
    { word: "live", meaning: "居住", partOfSpeech: "v" },
    { word: "living room", meaning: "客廳", partOfSpeech: "n" },
    { word: "local", meaning: "當地的", partOfSpeech: "adj" },
    { word: "lock", meaning: "鎖", partOfSpeech: "n" },
    { word: "lonely", meaning: "孤獨的", partOfSpeech: "adj" },
    { word: "long", meaning: "長的", partOfSpeech: "adj" },
    { word: "look", meaning: "看", partOfSpeech: "v" },
    { word: "lose", meaning: "失去", partOfSpeech: "v" },
    { word: "lot", meaning: "很多", partOfSpeech: "n" },
    { word: "loud", meaning: "大聲的", partOfSpeech: "adj" },
    { word: "love", meaning: "愛", partOfSpeech: "v" },
    { word: "low", meaning: "低的", partOfSpeech: "adj" },
    { word: "lucky", meaning: "幸運的", partOfSpeech: "adj" },
    { word: "lunch", meaning: "午餐", partOfSpeech: "n" },
    
    // M
    { word: "machine", meaning: "機器", partOfSpeech: "n" },
    { word: "magazine", meaning: "雜誌", partOfSpeech: "n" },
    { word: "magic", meaning: "魔法", partOfSpeech: "n" },
    { word: "mail", meaning: "郵件", partOfSpeech: "n" },
    { word: "main", meaning: "主要的", partOfSpeech: "adj" },
    { word: "make", meaning: "製作", partOfSpeech: "v" },
    { word: "man", meaning: "男人", partOfSpeech: "n" },
    { word: "many", meaning: "許多", partOfSpeech: "adj" },
    { word: "map", meaning: "地圖", partOfSpeech: "n" },
    { word: "March", meaning: "三月", partOfSpeech: "n" },
    { word: "mark", meaning: "標記", partOfSpeech: "n" },
    { word: "market", meaning: "市場", partOfSpeech: "n" },
    { word: "marry", meaning: "結婚", partOfSpeech: "v" },
    { word: "match", meaning: "匹配", partOfSpeech: "v" },
    { word: "math", meaning: "數學", partOfSpeech: "n" },
    { word: "matter", meaning: "事情", partOfSpeech: "n" },
    { word: "may", meaning: "可能", partOfSpeech: "v" },
    { word: "May", meaning: "五月", partOfSpeech: "n" },
    { word: "maybe", meaning: "或許", partOfSpeech: "adv" },
    { word: "me", meaning: "我(受格)", partOfSpeech: "pron" },
    { word: "meal", meaning: "餐", partOfSpeech: "n" },
    { word: "mean", meaning: "意思是", partOfSpeech: "v" },
    { word: "meat", meaning: "肉", partOfSpeech: "n" },
    { word: "medicine", meaning: "藥", partOfSpeech: "n" },
    { word: "meet", meaning: "遇見", partOfSpeech: "v" },
    { word: "meeting", meaning: "會議", partOfSpeech: "n" },
    { word: "member", meaning: "成員", partOfSpeech: "n" },
    { word: "memory", meaning: "記憶", partOfSpeech: "n" },
    { word: "menu", meaning: "菜單", partOfSpeech: "n" },
    { word: "message", meaning: "訊息", partOfSpeech: "n" },
    { word: "metal", meaning: "金屬", partOfSpeech: "n" },
    { word: "middle", meaning: "中間", partOfSpeech: "n" },
    { word: "midnight", meaning: "午夜", partOfSpeech: "n" },
    { word: "might", meaning: "可能", partOfSpeech: "v" },
    { word: "mile", meaning: "英里", partOfSpeech: "n" },
    { word: "milk", meaning: "牛奶", partOfSpeech: "n" },
    { word: "mind", meaning: "介意", partOfSpeech: "v" },
    { word: "minute", meaning: "分鐘", partOfSpeech: "n" },
    { word: "miss", meaning: "想念", partOfSpeech: "v" },
    { word: "mistake", meaning: "錯誤", partOfSpeech: "n" },
    { word: "mix", meaning: "混合", partOfSpeech: "v" },
    { word: "model", meaning: "模型", partOfSpeech: "n" },
    { word: "modern", meaning: "現代的", partOfSpeech: "adj" },
    { word: "moment", meaning: "片刻", partOfSpeech: "n" },
    { word: "Monday", meaning: "星期一", partOfSpeech: "n" },
    { word: "money", meaning: "錢", partOfSpeech: "n" },
    { word: "monkey", meaning: "猴子", partOfSpeech: "n" },
    { word: "month", meaning: "月", partOfSpeech: "n" },
    { word: "moon", meaning: "月亮", partOfSpeech: "n" },
    { word: "more", meaning: "更多", partOfSpeech: "adj" },
    { word: "morning", meaning: "早晨", partOfSpeech: "n" },
    { word: "most", meaning: "最多", partOfSpeech: "adj" },
    { word: "mother", meaning: "母親", partOfSpeech: "n" },
    { word: "mountain", meaning: "山", partOfSpeech: "n" },
    { word: "mouse", meaning: "老鼠", partOfSpeech: "n" },
    { word: "mouth", meaning: "嘴", partOfSpeech: "n" },
    { word: "move", meaning: "移動", partOfSpeech: "v" },
    { word: "movie", meaning: "電影", partOfSpeech: "n" },
    { word: "Mr.", meaning: "先生", partOfSpeech: "n" },
    { word: "Mrs.", meaning: "太太", partOfSpeech: "n" },
    { word: "Ms.", meaning: "女士", partOfSpeech: "n" },
    { word: "much", meaning: "許多", partOfSpeech: "adj" },
    { word: "museum", meaning: "博物館", partOfSpeech: "n" },
    { word: "music", meaning: "音樂", partOfSpeech: "n" },
    { word: "must", meaning: "必須", partOfSpeech: "v" },
    { word: "my", meaning: "我的", partOfSpeech: "pron" },
    { word: "myself", meaning: "我自己", partOfSpeech: "pron" },
    
    // N
    { word: "name", meaning: "名字", partOfSpeech: "n" },
    { word: "national", meaning: "國家的", partOfSpeech: "adj" },
    { word: "nature", meaning: "自然", partOfSpeech: "n" },
    { word: "near", meaning: "靠近", partOfSpeech: "prep" },
    { word: "neck", meaning: "脖子", partOfSpeech: "n" },
    { word: "need", meaning: "需要", partOfSpeech: "v" },
    { word: "neighbor", meaning: "鄰居", partOfSpeech: "n" },
    { word: "neither", meaning: "兩者都不", partOfSpeech: "conj" },
    { word: "never", meaning: "從不", partOfSpeech: "adv" },
    { word: "new", meaning: "新的", partOfSpeech: "adj" },
    { word: "news", meaning: "新聞", partOfSpeech: "n" },
    { word: "newspaper", meaning: "報紙", partOfSpeech: "n" },
    { word: "next", meaning: "下一個", partOfSpeech: "adj" },
    { word: "nice", meaning: "好的", partOfSpeech: "adj" },
    { word: "night", meaning: "夜晚", partOfSpeech: "n" },
    { word: "nine", meaning: "九", partOfSpeech: "num" },
    { word: "nineteen", meaning: "十九", partOfSpeech: "num" },
    { word: "ninety", meaning: "九十", partOfSpeech: "num" },
    { word: "no", meaning: "不", partOfSpeech: "adv" },
    { word: "nobody", meaning: "沒有人", partOfSpeech: "pron" },
    { word: "noise", meaning: "噪音", partOfSpeech: "n" },
    { word: "none", meaning: "沒有一個", partOfSpeech: "pron" },
    { word: "noon", meaning: "中午", partOfSpeech: "n" },
    { word: "nor", meaning: "也不", partOfSpeech: "conj" },
    { word: "north", meaning: "北方", partOfSpeech: "n" },
    { word: "nose", meaning: "鼻子", partOfSpeech: "n" },
    { word: "not", meaning: "不", partOfSpeech: "adv" },
    { word: "note", meaning: "筆記", partOfSpeech: "n" },
    { word: "nothing", meaning: "沒有東西", partOfSpeech: "pron" },
    { word: "notice", meaning: "注意", partOfSpeech: "v" },
    { word: "November", meaning: "十一月", partOfSpeech: "n" },
    { word: "now", meaning: "現在", partOfSpeech: "adv" },
    { word: "number", meaning: "數字", partOfSpeech: "n" },
    { word: "nurse", meaning: "護士", partOfSpeech: "n" },
    
    // O
    { word: "o'clock", meaning: "...點鐘", partOfSpeech: "adv" },
    { word: "October", meaning: "十月", partOfSpeech: "n" },
    { word: "of", meaning: "...的", partOfSpeech: "prep" },
    { word: "off", meaning: "離開", partOfSpeech: "adv" },
    { word: "offer", meaning: "提供", partOfSpeech: "v" },
    { word: "office", meaning: "辦公室", partOfSpeech: "n" },
    { word: "officer", meaning: "警官", partOfSpeech: "n" },
    { word: "often", meaning: "經常", partOfSpeech: "adv" },
    { word: "oil", meaning: "油", partOfSpeech: "n" },
    { word: "OK", meaning: "好的", partOfSpeech: "adj" },
    { word: "old", meaning: "老的", partOfSpeech: "adj" },
    { word: "on", meaning: "在...上", partOfSpeech: "prep" },
    { word: "once", meaning: "一次", partOfSpeech: "adv" },
    { word: "one", meaning: "一", partOfSpeech: "num" },
    { word: "only", meaning: "只有", partOfSpeech: "adv" },
    { word: "open", meaning: "打開", partOfSpeech: "v" },
    { word: "or", meaning: "或者", partOfSpeech: "conj" },
    { word: "orange", meaning: "橙子", partOfSpeech: "n" },
    { word: "order", meaning: "命令", partOfSpeech: "n" },
    { word: "other", meaning: "其他", partOfSpeech: "adj" },
    { word: "our", meaning: "我們的", partOfSpeech: "pron" },
    { word: "out", meaning: "出去", partOfSpeech: "adv" },
    { word: "outside", meaning: "外面", partOfSpeech: "adv" },
    { word: "over", meaning: "在...上方", partOfSpeech: "prep" },
    { word: "own", meaning: "擁有", partOfSpeech: "v" },
    
    // P
    { word: "page", meaning: "頁", partOfSpeech: "n" },
    { word: "pain", meaning: "疼痛", partOfSpeech: "n" },
    { word: "paint", meaning: "油漆", partOfSpeech: "n" },
    { word: "pair", meaning: "一對", partOfSpeech: "n" },
    { word: "pants", meaning: "褲子", partOfSpeech: "n" },
    { word: "paper", meaning: "紙", partOfSpeech: "n" },
    { word: "parent", meaning: "父母", partOfSpeech: "n" },
    { word: "park", meaning: "公園", partOfSpeech: "n" },
    { word: "part", meaning: "部分", partOfSpeech: "n" },
    { word: "party", meaning: "派對", partOfSpeech: "n" },
    { word: "pass", meaning: "通過", partOfSpeech: "v" },
    { word: "past", meaning: "過去", partOfSpeech: "n" },
    { word: "pay", meaning: "支付", partOfSpeech: "v" },
    { word: "pen", meaning: "筆", partOfSpeech: "n" },
    { word: "pencil", meaning: "鉛筆", partOfSpeech: "n" },
    { word: "people", meaning: "人們", partOfSpeech: "n" },
    { word: "perfect", meaning: "完美的", partOfSpeech: "adj" },
    { word: "perhaps", meaning: "或許", partOfSpeech: "adv" },
    { word: "person", meaning: "人", partOfSpeech: "n" },
    { word: "pet", meaning: "寵物", partOfSpeech: "n" },
    { word: "phone", meaning: "電話", partOfSpeech: "n" },
    { word: "photo", meaning: "照片", partOfSpeech: "n" },
    { word: "pick", meaning: "挑選", partOfSpeech: "v" },
    { word: "picnic", meaning: "野餐", partOfSpeech: "n" },
    { word: "picture", meaning: "圖片", partOfSpeech: "n" },
    { word: "piece", meaning: "片", partOfSpeech: "n" },
    { word: "pig", meaning: "豬", partOfSpeech: "n" },
    { word: "pink", meaning: "粉紅色", partOfSpeech: "n" },
    { word: "place", meaning: "地方", partOfSpeech: "n" },
    { word: "plan", meaning: "計劃", partOfSpeech: "n" },
    { word: "plane", meaning: "飛機", partOfSpeech: "n" },
    { word: "plant", meaning: "植物", partOfSpeech: "n" },
    { word: "plate", meaning: "盤子", partOfSpeech: "n" },
    { word: "play", meaning: "玩", partOfSpeech: "v" },
    { word: "player", meaning: "選手", partOfSpeech: "n" },
    { word: "please", meaning: "請", partOfSpeech: "v" },
    { word: "pleasure", meaning: "愉快", partOfSpeech: "n" },
    { word: "pocket", meaning: "口袋", partOfSpeech: "n" },
    { word: "point", meaning: "點", partOfSpeech: "n" },
    { word: "police", meaning: "警察", partOfSpeech: "n" },
    { word: "poor", meaning: "貧窮的", partOfSpeech: "adj" },
    { word: "popular", meaning: "受歡迎的", partOfSpeech: "adj" },
    { word: "pork", meaning: "豬肉", partOfSpeech: "n" },
    { word: "possible", meaning: "可能的", partOfSpeech: "adj" },
    { word: "post", meaning: "郵寄", partOfSpeech: "v" },
    { word: "post office", meaning: "郵局", partOfSpeech: "n" },
    { word: "postcard", meaning: "明信片", partOfSpeech: "n" },
    { word: "pot", meaning: "鍋", partOfSpeech: "n" },
    { word: "potato", meaning: "馬鈴薯", partOfSpeech: "n" },
    { word: "pound", meaning: "磅", partOfSpeech: "n" },
    { word: "power", meaning: "力量", partOfSpeech: "n" },
    { word: "practice", meaning: "練習", partOfSpeech: "n" },
    { word: "prepare", meaning: "準備", partOfSpeech: "v" },
    { word: "present", meaning: "禮物", partOfSpeech: "n" },
    { word: "pretty", meaning: "漂亮的", partOfSpeech: "adj" },
    { word: "price", meaning: "價格", partOfSpeech: "n" },
    { word: "problem", meaning: "問題", partOfSpeech: "n" },
    { word: "program", meaning: "節目", partOfSpeech: "n" },
    { word: "proud", meaning: "驕傲的", partOfSpeech: "adj" },
    { word: "public", meaning: "公共的", partOfSpeech: "adj" },
    { word: "pull", meaning: "拉", partOfSpeech: "v" },
    { word: "purple", meaning: "紫色的", partOfSpeech: "adj" },
    { word: "push", meaning: "推", partOfSpeech: "v" },
    { word: "put", meaning: "放", partOfSpeech: "v" },
    
    // Q
    { word: "question", meaning: "問題", partOfSpeech: "n" },
    { word: "quick", meaning: "快的", partOfSpeech: "adj" },
    { word: "quiet", meaning: "安靜的", partOfSpeech: "adj" },
    { word: "quite", meaning: "相當", partOfSpeech: "adv" },
    
    // R
    { word: "rabbit", meaning: "兔子", partOfSpeech: "n" },
    { word: "race", meaning: "比賽", partOfSpeech: "n" },
    { word: "radio", meaning: "收音機", partOfSpeech: "n" },
    { word: "rain", meaning: "雨", partOfSpeech: "n" },
    { word: "rainbow", meaning: "彩虹", partOfSpeech: "n" },
    { word: "rainy", meaning: "下雨的", partOfSpeech: "adj" },
    { word: "raise", meaning: "舉起", partOfSpeech: "v" },
    { word: "read", meaning: "閱讀", partOfSpeech: "v" },
    { word: "ready", meaning: "準備好的", partOfSpeech: "adj" },
    { word: "real", meaning: "真實的", partOfSpeech: "adj" },
    { word: "really", meaning: "真的", partOfSpeech: "adv" },
    { word: "reason", meaning: "理由", partOfSpeech: "n" },
    { word: "receive", meaning: "收到", partOfSpeech: "v" },
    { word: "record", meaning: "記錄", partOfSpeech: "n" },
    { word: "red", meaning: "紅色的", partOfSpeech: "adj" },
    { word: "refrigerator", meaning: "冰箱", partOfSpeech: "n" },
    { word: "remember", meaning: "記得", partOfSpeech: "v" },
    { word: "rent", meaning: "租", partOfSpeech: "v" },
    { word: "repair", meaning: "修理", partOfSpeech: "v" },
    { word: "repeat", meaning: "重複", partOfSpeech: "v" },
    { word: "report", meaning: "報告", partOfSpeech: "n" },
    { word: "rest", meaning: "休息", partOfSpeech: "v" },
    { word: "restaurant", meaning: "餐廳", partOfSpeech: "n" },
    { word: "return", meaning: "返回", partOfSpeech: "v" },
    { word: "rice", meaning: "米飯", partOfSpeech: "n" },
    { word: "rich", meaning: "富有的", partOfSpeech: "adj" },
    { word: "ride", meaning: "騎", partOfSpeech: "v" },
    { word: "right", meaning: "右邊的", partOfSpeech: "adj" },
    { word: "ring", meaning: "戒指", partOfSpeech: "n" },
    { word: "river", meaning: "河流", partOfSpeech: "n" },
    { word: "road", meaning: "道路", partOfSpeech: "n" },
    { word: "robot", meaning: "機器人", partOfSpeech: "n" },
    { word: "rock", meaning: "岩石", partOfSpeech: "n" },
    { word: "room", meaning: "房間", partOfSpeech: "n" },
    { word: "round", meaning: "圓的", partOfSpeech: "adj" },
    { word: "rule", meaning: "規則", partOfSpeech: "n" },
    { word: "ruler", meaning: "尺", partOfSpeech: "n" },
    { word: "run", meaning: "跑", partOfSpeech: "v" },
    
    // S
    { word: "sad", meaning: "悲傷的", partOfSpeech: "adj" },
    { word: "safe", meaning: "安全的", partOfSpeech: "adj" },
    { word: "salad", meaning: "沙拉", partOfSpeech: "n" },
    { word: "sale", meaning: "銷售", partOfSpeech: "n" },
    { word: "salt", meaning: "鹽", partOfSpeech: "n" },
    { word: "same", meaning: "相同的", partOfSpeech: "adj" },
    { word: "sandwich", meaning: "三明治", partOfSpeech: "n" },
    { word: "Saturday", meaning: "星期六", partOfSpeech: "n" },
    { word: "save", meaning: "節省", partOfSpeech: "v" },
    { word: "say", meaning: "說", partOfSpeech: "v" },
    { word: "school", meaning: "學校", partOfSpeech: "n" },
    { word: "science", meaning: "科學", partOfSpeech: "n" },
    { word: "scissors", meaning: "剪刀", partOfSpeech: "n" },
    { word: "sea", meaning: "海", partOfSpeech: "n" },
    { word: "season", meaning: "季節", partOfSpeech: "n" },
    { word: "seat", meaning: "座位", partOfSpeech: "n" },
    { word: "second", meaning: "第二", partOfSpeech: "num" },
    { word: "see", meaning: "看見", partOfSpeech: "v" },
    { word: "seem", meaning: "似乎", partOfSpeech: "v" },
    { word: "sell", meaning: "賣", partOfSpeech: "v" },
    { word: "send", meaning: "發送", partOfSpeech: "v" },
    { word: "sentence", meaning: "句子", partOfSpeech: "n" },
    { word: "September", meaning: "九月", partOfSpeech: "n" },
    { word: "serious", meaning: "嚴肅的", partOfSpeech: "adj" },
    { word: "serve", meaning: "服務", partOfSpeech: "v" },
    { word: "seven", meaning: "七", partOfSpeech: "num" },
    { word: "seventeen", meaning: "十七", partOfSpeech: "num" },
    { word: "seventy", meaning: "七十", partOfSpeech: "num" },
    { word: "several", meaning: "幾個", partOfSpeech: "adj" },
    { word: "shall", meaning: "將要", partOfSpeech: "v" },
    { word: "shape", meaning: "形狀", partOfSpeech: "n" },
    { word: "share", meaning: "分享", partOfSpeech: "v" },
    { word: "she", meaning: "她", partOfSpeech: "pron" },
    { word: "sheep", meaning: "綿羊", partOfSpeech: "n" },
    { word: "shirt", meaning: "襯衫", partOfSpeech: "n" },
    { word: "shoe", meaning: "鞋", partOfSpeech: "n" },
    { word: "shop", meaning: "商店", partOfSpeech: "n" },
    { word: "shopping", meaning: "購物", partOfSpeech: "n" },
    { word: "short", meaning: "短的", partOfSpeech: "adj" },
    { word: "should", meaning: "應該", partOfSpeech: "v" },
    { word: "shoulder", meaning: "肩膀", partOfSpeech: "n" },
    { word: "show", meaning: "展示", partOfSpeech: "v" },
    { word: "shower", meaning: "淋浴", partOfSpeech: "n" },
    { word: "sick", meaning: "生病的", partOfSpeech: "adj" },
    { word: "side", meaning: "側面", partOfSpeech: "n" },
    { word: "sign", meaning: "標誌", partOfSpeech: "n" },
    { word: "simple", meaning: "簡單的", partOfSpeech: "adj" },
    { word: "since", meaning: "自從", partOfSpeech: "prep" },
    { word: "sing", meaning: "唱歌", partOfSpeech: "v" },
    { word: "singer", meaning: "歌手", partOfSpeech: "n" },
    { word: "single", meaning: "單一的", partOfSpeech: "adj" },
    { word: "sister", meaning: "姐妹", partOfSpeech: "n" },
    { word: "sit", meaning: "坐", partOfSpeech: "v" },
    { word: "six", meaning: "六", partOfSpeech: "num" },
    { word: "sixteen", meaning: "十六", partOfSpeech: "num" },
    { word: "sixty", meaning: "六十", partOfSpeech: "num" },
    { word: "size", meaning: "尺寸", partOfSpeech: "n" },
    { word: "skate", meaning: "溜冰", partOfSpeech: "v" },
    { word: "ski", meaning: "滑雪", partOfSpeech: "v" },
    { word: "sky", meaning: "天空", partOfSpeech: "n" },
    { word: "sleep", meaning: "睡覺", partOfSpeech: "v" },
    { word: "slow", meaning: "慢的", partOfSpeech: "adj" },
    { word: "small", meaning: "小的", partOfSpeech: "adj" },
    { word: "smart", meaning: "聰明的", partOfSpeech: "adj" },
    { word: "smell", meaning: "聞", partOfSpeech: "v" },
    { word: "smile", meaning: "微笑", partOfSpeech: "v" },
    { word: "smoke", meaning: "煙", partOfSpeech: "n" },
    { word: "snack", meaning: "點心", partOfSpeech: "n" },
    { word: "snake", meaning: "蛇", partOfSpeech: "n" },
    { word: "snow", meaning: "雪", partOfSpeech: "n" },
    { word: "so", meaning: "所以", partOfSpeech: "adv" },
    { word: "soap", meaning: "肥皂", partOfSpeech: "n" },
    { word: "soccer", meaning: "足球", partOfSpeech: "n" },
    { word: "social", meaning: "社交的", partOfSpeech: "adj" },
    { word: "sock", meaning: "襪子", partOfSpeech: "n" },
    { word: "sofa", meaning: "沙發", partOfSpeech: "n" },
    { word: "soft", meaning: "軟的", partOfSpeech: "adj" },
    { word: "some", meaning: "一些", partOfSpeech: "adj" },
    { word: "someone", meaning: "某人", partOfSpeech: "pron" },
    { word: "something", meaning: "某事", partOfSpeech: "pron" },
    { word: "sometimes", meaning: "有時", partOfSpeech: "adv" },
    { word: "son", meaning: "兒子", partOfSpeech: "n" },
    { word: "song", meaning: "歌曲", partOfSpeech: "n" },
    { word: "soon", meaning: "很快", partOfSpeech: "adv" },
    { word: "sorry", meaning: "抱歉", partOfSpeech: "adj" },
    { word: "sound", meaning: "聲音", partOfSpeech: "n" },
    { word: "soup", meaning: "湯", partOfSpeech: "n" },
    { word: "south", meaning: "南方", partOfSpeech: "n" },
    { word: "space", meaning: "空間", partOfSpeech: "n" },
    { word: "speak", meaning: "說話", partOfSpeech: "v" },
    { word: "special", meaning: "特別的", partOfSpeech: "adj" },
    { word: "spell", meaning: "拼寫", partOfSpeech: "v" },
    { word: "spend", meaning: "花費", partOfSpeech: "v" },
    { word: "spoon", meaning: "湯匙", partOfSpeech: "n" },
    { word: "sport", meaning: "運動", partOfSpeech: "n" },
    { word: "spring", meaning: "春天", partOfSpeech: "n" },
    { word: "square", meaning: "正方形", partOfSpeech: "n" },
    { word: "stairs", meaning: "樓梯", partOfSpeech: "n" },
    { word: "stand", meaning: "站立", partOfSpeech: "v" },
    { word: "star", meaning: "星星", partOfSpeech: "n" },
    { word: "start", meaning: "開始", partOfSpeech: "v" },
    { word: "station", meaning: "車站", partOfSpeech: "n" },
    { word: "stay", meaning: "停留", partOfSpeech: "v" },
    { word: "steak", meaning: "牛排", partOfSpeech: "n" },
    { word: "still", meaning: "仍然", partOfSpeech: "adv" },
    { word: "stomach", meaning: "胃", partOfSpeech: "n" },
    { word: "stop", meaning: "停止", partOfSpeech: "v" },
    { word: "store", meaning: "商店", partOfSpeech: "n" },
    { word: "story", meaning: "故事", partOfSpeech: "n" },
    { word: "straight", meaning: "直的", partOfSpeech: "adj" },
    { word: "strange", meaning: "奇怪的", partOfSpeech: "adj" },
    { word: "street", meaning: "街道", partOfSpeech: "n" },
    { word: "strong", meaning: "強壯的", partOfSpeech: "adj" },
    { word: "student", meaning: "學生", partOfSpeech: "n" },
    { word: "study", meaning: "學習", partOfSpeech: "v" },
    { word: "subject", meaning: "科目", partOfSpeech: "n" },
    { word: "such", meaning: "如此", partOfSpeech: "adj" },
    { word: "suddenly", meaning: "突然地", partOfSpeech: "adv" },
    { word: "sugar", meaning: "糖", partOfSpeech: "n" },
    { word: "summer", meaning: "夏天", partOfSpeech: "n" },
    { word: "sun", meaning: "太陽", partOfSpeech: "n" },
    { word: "Sunday", meaning: "星期日", partOfSpeech: "n" },
    { word: "sunny", meaning: "晴朗的", partOfSpeech: "adj" },
    { word: "supermarket", meaning: "超市", partOfSpeech: "n" },
    { word: "sure", meaning: "確定的", partOfSpeech: "adj" },
    { word: "surprise", meaning: "驚喜", partOfSpeech: "n" },
    { word: "sweater", meaning: "毛衣", partOfSpeech: "n" },
    { word: "sweet", meaning: "甜的", partOfSpeech: "adj" },
    { word: "swim", meaning: "游泳", partOfSpeech: "v" },
    
    // T
    { word: "table", meaning: "桌子", partOfSpeech: "n" },
    { word: "take", meaning: "拿", partOfSpeech: "v" },
    { word: "talk", meaning: "談話", partOfSpeech: "v" },
    { word: "tall", meaning: "高的", partOfSpeech: "adj" },
    { word: "tape", meaning: "磁帶", partOfSpeech: "n" },
    { word: "taste", meaning: "味道", partOfSpeech: "n" },
    { word: "taxi", meaning: "計程車", partOfSpeech: "n" },
    { word: "tea", meaning: "茶", partOfSpeech: "n" },
    { word: "teach", meaning: "教", partOfSpeech: "v" },
    { word: "teacher", meaning: "老師", partOfSpeech: "n" },
    { word: "team", meaning: "團隊", partOfSpeech: "n" },
    { word: "teenager", meaning: "青少年", partOfSpeech: "n" },
    { word: "telephone", meaning: "電話", partOfSpeech: "n" },
    { word: "television", meaning: "電視", partOfSpeech: "n" },
    { word: "tell", meaning: "告訴", partOfSpeech: "v" },
    { word: "ten", meaning: "十", partOfSpeech: "num" },
    { word: "tennis", meaning: "網球", partOfSpeech: "n" },
    { word: "test", meaning: "測試", partOfSpeech: "n" },
    { word: "than", meaning: "比", partOfSpeech: "conj" },
    { word: "thank", meaning: "感謝", partOfSpeech: "v" },
    { word: "that", meaning: "那個", partOfSpeech: "pron" },
    { word: "the", meaning: "這個", partOfSpeech: "art" },
    { word: "theater", meaning: "劇院", partOfSpeech: "n" },
    { word: "their", meaning: "他們的", partOfSpeech: "pron" },
    { word: "them", meaning: "他們", partOfSpeech: "pron" },
    { word: "then", meaning: "然後", partOfSpeech: "adv" },
    { word: "there", meaning: "那裡", partOfSpeech: "adv" },
    { word: "these", meaning: "這些", partOfSpeech: "pron" },
    { word: "they", meaning: "他們", partOfSpeech: "pron" },
    { word: "thick", meaning: "厚的", partOfSpeech: "adj" },
    { word: "thin", meaning: "薄的", partOfSpeech: "adj" },
    { word: "thing", meaning: "事物", partOfSpeech: "n" },
    { word: "think", meaning: "思考", partOfSpeech: "v" },
    { word: "third", meaning: "第三", partOfSpeech: "num" },
    { word: "thirsty", meaning: "口渴的", partOfSpeech: "adj" },
    { word: "thirteen", meaning: "十三", partOfSpeech: "num" },
    { word: "thirty", meaning: "三十", partOfSpeech: "num" },
    { word: "this", meaning: "這個", partOfSpeech: "pron" },
    { word: "those", meaning: "那些", partOfSpeech: "pron" },
    { word: "though", meaning: "雖然", partOfSpeech: "conj" },
    { word: "thousand", meaning: "千", partOfSpeech: "num" },
    { word: "three", meaning: "三", partOfSpeech: "num" },
    { word: "through", meaning: "穿過", partOfSpeech: "prep" },
    { word: "throw", meaning: "投擲", partOfSpeech: "v" },
    { word: "Thursday", meaning: "星期四", partOfSpeech: "n" },
    { word: "ticket", meaning: "票", partOfSpeech: "n" },
    { word: "tidy", meaning: "整潔的", partOfSpeech: "adj" },
    { word: "tie", meaning: "領帶", partOfSpeech: "n" },
    { word: "tiger", meaning: "老虎", partOfSpeech: "n" },
    { word: "time", meaning: "時間", partOfSpeech: "n" },
    { word: "tired", meaning: "疲倦的", partOfSpeech: "adj" },
    { word: "to", meaning: "到", partOfSpeech: "prep" },
    { word: "today", meaning: "今天", partOfSpeech: "n" },
    { word: "together", meaning: "一起", partOfSpeech: "adv" },
    { word: "toilet", meaning: "廁所", partOfSpeech: "n" },
    { word: "tomato", meaning: "番茄", partOfSpeech: "n" },
    { word: "tomorrow", meaning: "明天", partOfSpeech: "n" },
    { word: "tonight", meaning: "今晚", partOfSpeech: "n" },
    { word: "too", meaning: "也", partOfSpeech: "adv" },
    { word: "tooth", meaning: "牙齒", partOfSpeech: "n" },
    { word: "toothbrush", meaning: "牙刷", partOfSpeech: "n" },
    { word: "top", meaning: "頂部", partOfSpeech: "n" },
    { word: "touch", meaning: "觸摸", partOfSpeech: "v" },
    { word: "towel", meaning: "毛巾", partOfSpeech: "n" },
    { word: "town", meaning: "城鎮", partOfSpeech: "n" },
    { word: "toy", meaning: "玩具", partOfSpeech: "n" },
    { word: "traffic", meaning: "交通", partOfSpeech: "n" },
    { word: "train", meaning: "火車", partOfSpeech: "n" },
    { word: "travel", meaning: "旅行", partOfSpeech: "v" },
    { word: "tree", meaning: "樹", partOfSpeech: "n" },
    { word: "trip", meaning: "旅行", partOfSpeech: "n" },
    { word: "trouble", meaning: "麻煩", partOfSpeech: "n" },
    { word: "truck", meaning: "卡車", partOfSpeech: "n" },
    { word: "true", meaning: "真實的", partOfSpeech: "adj" },
    { word: "try", meaning: "嘗試", partOfSpeech: "v" },
    { word: "T-shirt", meaning: "T恤", partOfSpeech: "n" },
    { word: "Tuesday", meaning: "星期二", partOfSpeech: "n" },
    { word: "turn", meaning: "轉", partOfSpeech: "v" },
    { word: "TV", meaning: "電視", partOfSpeech: "n" },
    { word: "twelve", meaning: "十二", partOfSpeech: "num" },
    { word: "twenty", meaning: "二十", partOfSpeech: "num" },
    { word: "twice", meaning: "兩次", partOfSpeech: "adv" },
    { word: "two", meaning: "二", partOfSpeech: "num" },
    { word: "type", meaning: "類型", partOfSpeech: "n" },
    
    // U
    { word: "umbrella", meaning: "雨傘", partOfSpeech: "n" },
    { word: "uncle", meaning: "叔叔", partOfSpeech: "n" },
    { word: "under", meaning: "在...下", partOfSpeech: "prep" },
    { word: "understand", meaning: "理解", partOfSpeech: "v" },
    { word: "uniform", meaning: "制服", partOfSpeech: "n" },
    { word: "until", meaning: "直到", partOfSpeech: "prep" },
    { word: "up", meaning: "向上", partOfSpeech: "adv" },
    { word: "us", meaning: "我們", partOfSpeech: "pron" },
    { word: "use", meaning: "使用", partOfSpeech: "v" },
    { word: "useful", meaning: "有用的", partOfSpeech: "adj" },
    { word: "usual", meaning: "通常的", partOfSpeech: "adj" },
    { word: "usually", meaning: "通常", partOfSpeech: "adv" },
    
    // V
    { word: "vacation", meaning: "假期", partOfSpeech: "n" },
    { word: "vegetable", meaning: "蔬菜", partOfSpeech: "n" },
    { word: "very", meaning: "非常", partOfSpeech: "adv" },
    { word: "video", meaning: "視頻", partOfSpeech: "n" },
    { word: "view", meaning: "景色", partOfSpeech: "n" },
    { word: "village", meaning: "村莊", partOfSpeech: "n" },
    { word: "visit", meaning: "拜訪", partOfSpeech: "v" },
    { word: "visitor", meaning: "訪客", partOfSpeech: "n" },
    { word: "voice", meaning: "聲音", partOfSpeech: "n" },
    { word: "volleyball", meaning: "排球", partOfSpeech: "n" },
    
    // W
    { word: "wait", meaning: "等待", partOfSpeech: "v" },
    { word: "waiter", meaning: "服務員", partOfSpeech: "n" },
    { word: "waitress", meaning: "女服務員", partOfSpeech: "n" },
    { word: "wake", meaning: "醒來", partOfSpeech: "v" },
    { word: "walk", meaning: "走路", partOfSpeech: "v" },
    { word: "wall", meaning: "牆", partOfSpeech: "n" },
    { word: "want", meaning: "想要", partOfSpeech: "v" },
    { word: "warm", meaning: "溫暖的", partOfSpeech: "adj" },
    { word: "wash", meaning: "洗", partOfSpeech: "v" },
    { word: "watch", meaning: "手錶", partOfSpeech: "n" },
    { word: "water", meaning: "水", partOfSpeech: "n" },
    { word: "way", meaning: "方式", partOfSpeech: "n" },
    { word: "we", meaning: "我們", partOfSpeech: "pron" },
    { word: "weak", meaning: "虛弱的", partOfSpeech: "adj" },
    { word: "wear", meaning: "穿", partOfSpeech: "v" },
    { word: "weather", meaning: "天氣", partOfSpeech: "n" },
    { word: "Wednesday", meaning: "星期三", partOfSpeech: "n" },
    { word: "week", meaning: "週", partOfSpeech: "n" },
    { word: "weekend", meaning: "週末", partOfSpeech: "n" },
    { word: "welcome", meaning: "歡迎", partOfSpeech: "v" },
    { word: "well", meaning: "好", partOfSpeech: "adv" },
    { word: "west", meaning: "西方", partOfSpeech: "n" },
    { word: "wet", meaning: "濕的", partOfSpeech: "adj" },
    { word: "what", meaning: "什麼", partOfSpeech: "pron" },
    { word: "when", meaning: "何時", partOfSpeech: "adv" },
    { word: "where", meaning: "哪裡", partOfSpeech: "adv" },
    { word: "which", meaning: "哪一個", partOfSpeech: "pron" },
    { word: "white", meaning: "白色的", partOfSpeech: "adj" },
    { word: "who", meaning: "誰", partOfSpeech: "pron" },
    { word: "whole", meaning: "整個", partOfSpeech: "adj" },
    { word: "whose", meaning: "誰的", partOfSpeech: "pron" },
    { word: "why", meaning: "為什麼", partOfSpeech: "adv" },
    { word: "wide", meaning: "寬的", partOfSpeech: "adj" },
    { word: "wife", meaning: "妻子", partOfSpeech: "n" },
    { word: "will", meaning: "將", partOfSpeech: "v" },
    { word: "win", meaning: "贏", partOfSpeech: "v" },
    { word: "wind", meaning: "風", partOfSpeech: "n" },
    { word: "window", meaning: "窗戶", partOfSpeech: "n" },
    { word: "windy", meaning: "多風的", partOfSpeech: "adj" },
    { word: "winter", meaning: "冬天", partOfSpeech: "n" },
    { word: "wish", meaning: "希望", partOfSpeech: "v" },
    { word: "with", meaning: "和", partOfSpeech: "prep" },
    { word: "without", meaning: "沒有", partOfSpeech: "prep" },
    { word: "woman", meaning: "女人", partOfSpeech: "n" },
    { word: "wonderful", meaning: "精彩的", partOfSpeech: "adj" },
    { word: "word", meaning: "單詞", partOfSpeech: "n" },
    { word: "work", meaning: "工作", partOfSpeech: "v" },
    { word: "worker", meaning: "工人", partOfSpeech: "n" },
    { word: "world", meaning: "世界", partOfSpeech: "n" },
    { word: "worry", meaning: "擔心", partOfSpeech: "v" },
    { word: "would", meaning: "將會", partOfSpeech: "v" },
    { word: "write", meaning: "寫", partOfSpeech: "v" },
    { word: "writer", meaning: "作家", partOfSpeech: "n" },
    { word: "wrong", meaning: "錯誤的", partOfSpeech: "adj" },
    
    // Y
    { word: "yard", meaning: "院子", partOfSpeech: "n" },
    { word: "year", meaning: "年", partOfSpeech: "n" },
    { word: "yellow", meaning: "黃色的", partOfSpeech: "adj" },
    { word: "yes", meaning: "是", partOfSpeech: "adv" },
    { word: "yesterday", meaning: "昨天", partOfSpeech: "n" },
    { word: "yet", meaning: "還", partOfSpeech: "adv" },
    { word: "you", meaning: "你", partOfSpeech: "pron" },
    { word: "young", meaning: "年輕的", partOfSpeech: "adj" },
    { word: "your", meaning: "你的", partOfSpeech: "pron" },
    { word: "yourself", meaning: "你自己", partOfSpeech: "pron" },
    
    // Z
    { word: "zero", meaning: "零", partOfSpeech: "num" },
    { word: "zoo", meaning: "動物園", partOfSpeech: "n" }
];

// 匯入單字到應用程式
function importBasic1200Words() {
    console.log('開始匯入台灣國中英文基礎1200單字...');
    
    // 確保 window.appData 已初始化
    if (!window.appData) {
        console.log('window.appData 不存在，初始化為空對象');
        window.appData = {};
    }
    
    // 確保 window.appData.vocabulary 是一個陣列
    if (!window.appData.vocabulary) {
        console.log('window.appData.vocabulary 不存在，初始化為空陣列');
        window.appData.vocabulary = [];
    } else if (!Array.isArray(window.appData.vocabulary)) {
        console.log('window.appData.vocabulary 不是陣列，重新初始化為空陣列');
        window.appData.vocabulary = [];
    }
    
    let importCount = 0;
    let skipCount = 0;
    
    // 檢查每個單字是否已存在
    basic1200Words.forEach(wordData => {
        // 檢查單字是否已存在
        const exists = window.appData.vocabulary.some(item => 
            item.word.toLowerCase() === wordData.word.toLowerCase()
        );
        
        if (!exists) {
            // 建立新單字物件
            const newWord = {
                id: Date.now() + Math.floor(Math.random() * 1000),
                word: wordData.word,
                phonetic: '',
                partOfSpeech: wordData.partOfSpeech,
                meaning: wordData.meaning,
                examples: [],
                status: 'new',
                dateAdded: new Date().toISOString(),
                lastReviewed: null
            };
            
            // 添加到詞彙列表
            window.appData.vocabulary.push(newWord);
            importCount++;
        } else {
            skipCount++;
        }
    });
    
    // 儲存到 localStorage
    try {
        localStorage.setItem('appData', JSON.stringify(window.appData));
        console.log(`匯入完成！成功匯入 ${importCount} 個單字，跳過 ${skipCount} 個已存在的單字。`);
        alert(`匯入完成！成功匯入 ${importCount} 個單字，跳過 ${skipCount} 個已存在的單字。`);
        
        // 重新載入詞彙列表
        if (typeof loadVocabularyData === 'function') {
            loadVocabularyData();
        } else {
            console.log('找不到 loadVocabularyData 函數，嘗試重新載入頁面');
            // 如果找不到 loadVocabularyData 函數，嘗試重新載入詞彙頁面
            const vocabNavLink = document.querySelector('nav a[data-page="vocabulary"]');
            if (vocabNavLink && typeof switchPage === 'function') {
                switchPage('vocabulary');
            }
        }
    } catch (error) {
        console.error('儲存到 localStorage 時發生錯誤:', error);
        alert('匯入過程中發生錯誤，請查看控制台獲取詳細信息。');
    }
}

// 添加匯入按鈕到頁面
function addImportButton() {
    const vocabPage = document.getElementById('vocabulary');
    if (!vocabPage) {
        console.error('找不到詞彙頁面，無法添加匯入按鈕');
        return;
    }
    
    // 嘗試找到 header-actions 容器
    const headerActions = vocabPage.querySelector('.header-actions');
    if (headerActions) {
        // 檢查按鈕是否已存在
        if (document.getElementById('importBasic1200Btn')) {
            return;
        }
        
        // 創建匯入按鈕
        const importBtn = document.createElement('button');
        importBtn.id = 'importBasic1200Btn';
        importBtn.className = 'primary-btn';
        importBtn.innerHTML = '<i class="fas fa-download"></i> 匯入國中基礎1200單字';
        importBtn.addEventListener('click', importBasic1200Words);
        
        // 添加到 header-actions 容器
        headerActions.appendChild(importBtn);
        console.log('已添加匯入按鈕到詞彙頁面的 header-actions');
        return;
    }
    
    // 如果找不到 header-actions，嘗試找到 dropdown-content 容器
    const dropdownContent = vocabPage.querySelector('.dropdown-content');
    if (dropdownContent) {
        // 檢查按鈕是否已存在
        if (document.getElementById('importBasic1200Btn')) {
            return;
        }
        
        // 創建匯入按鈕作為下拉選項
        const importBtn = document.createElement('button');
        importBtn.id = 'importBasic1200Btn';
        importBtn.className = 'dropdown-item';
        importBtn.innerHTML = '<i class="fas fa-download"></i> 匯入國中基礎1200單字';
        importBtn.addEventListener('click', importBasic1200Words);
        
        // 添加到下拉選單
        dropdownContent.appendChild(importBtn);
        console.log('已添加匯入按鈕到詞彙頁面的下拉選單');
        return;
    }
    
    console.error('找不到合適的容器來添加匯入按鈕');
}

// 當文檔加載完成時添加匯入按鈕
document.addEventListener('DOMContentLoaded', function() {
    // 等待一秒確保其他腳本已加載
    setTimeout(addImportButton, 1000);
});

// 如果文檔已經加載完成，立即添加按鈕
if (document.readyState === 'complete' || document.readyState === 'interactive') {
    setTimeout(addImportButton, 1000);
} 

// 監聽頁面切換事件，確保在切換到詞彙頁面時也能添加按鈕
document.addEventListener('click', function(e) {
    // 檢查是否點擊了導航鏈接
    if (e.target && (e.target.matches('nav a[data-page="vocabulary"]') || e.target.closest('nav a[data-page="vocabulary"]'))) {
        // 等待頁面切換完成後添加按鈕
        setTimeout(addImportButton, 500);
    }
});

// 定期檢查詞彙頁面是否可見，如果可見且沒有按鈕，則添加按鈕
setInterval(function() {
    const vocabPage = document.getElementById('vocabulary');
    if (vocabPage && vocabPage.classList.contains('active') && !document.getElementById('importBasic1200Btn')) {
        addImportButton();
    }
}, 2000); // 每2秒檢查一次